# Generated by Django 4.0.4 on 2022-07-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_contact_alter_product_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('items_json', models.CharField(max_length=50000)),
                ('name', models.CharField(default='', max_length=70)),
                ('email', models.CharField(default='', max_length=500)),
                ('address', models.CharField(default='', max_length=500)),
                ('city', models.CharField(default='', max_length=500)),
                ('state', models.CharField(default='', max_length=500)),
                ('zip_code', models.CharField(default='', max_length=500)),
                ('phone', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
